'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ACTIVE=new Set(['RUNNING','FINALIZING']);let current=null,activeRun=null,source=null,code={},attempts=[],tab='policy_diff',project=null,selection=0;
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error((await r.json()).detail||r.statusText);return r.json()}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),5000)}
function modal(title,content,action){$('modalTitle').textContent=title;$('modalBody').innerHTML=content;$('modalback').classList.remove('hidden');$('modalAction').classList.toggle('hidden',!action);$('modalAction').textContent='确认本地导出';$('modalAction').onclick=action||null;$('closeModal').focus()}
function close(){$('modalback').classList.add('hidden')}
$('closeModal').onclick=close;$('modalCloseBottom').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
function page(name){document.querySelectorAll('section[id^=page-]').forEach(e=>e.classList.toggle('hidden',e.id!=='page-'+name));document.querySelectorAll('.navbtn').forEach(e=>e.classList.toggle('active',e.dataset.page===name));if(name==='history')history();if(name==='skills')skills()}
document.querySelectorAll('.navbtn').forEach(e=>e.onclick=()=>page(e.dataset.page));
function renderCode(){const s=code[tab]||'本次运行尚无候选快照';$('codebox').innerHTML=s.split('\n').map((line,i)=>`<div class="codeline ${line.startsWith('+')?'add':line.startsWith('-')?'del':''}"><span class="num">${i+1}</span><span class="txt">${esc(line)}</span></div>`).join('');if(code.attempt!==undefined)$('codeNote').textContent='当前查看 attempt '+code.attempt+' / 候选 '+code.candidate_id.slice(0,12)+'；下面的检查属于此 attempt，顶部指标为运行最终结论。';$('filename').textContent=tab==='policy_diff'?'已冻结策略 / attempt '+(code.attempt??'—'):code.path||'尚无快照';document.querySelectorAll('.tab').forEach(e=>e.classList.toggle('active',e.dataset.tab===tab));renderChecks()}
document.querySelectorAll('.tab').forEach(e=>e.onclick=()=>{tab=e.dataset.tab;renderCode()});
$('expandCode').onclick=()=>$('codebox').classList.toggle('expanded');
$('attemptSelect').onchange=()=>{code=attempts.find(a=>String(a.attempt)===$('attemptSelect').value)||{};renderCode()};
const names={original_cpu:'原始 pandas / CPU',original_cudf_pandas:'原始 cudf.pandas',optimized_cpu_same_structure:'同构优化 pandas / CPU',optimized_gpu:'同构优化 cuDF / GPU'};
function activeUI(){const live=!!activeRun&&ACTIVE.has(activeRun.status);$('runBtn').disabled=live||!!window.OFFLINE;$('scenario').disabled=live;$('executionProfile').disabled=live;$('cancelBtn').classList.toggle('hidden',!live);$('activeBanner').classList.toggle('hidden',!live);if(live){$('activeBanner').innerHTML=`活动任务 <b>${esc(activeRun.id)}</b> · ${esc(activeRun.status)} <button class="btn sm" id="returnActive">返回活动任务</button><button class="btn danger sm" id="cancelActive">取消此任务</button>`;$('returnActive').onclick=()=>load(activeRun.id);$('cancelActive').onclick=cancelActive}}
function renderChecks(){const list=(code.checks||current?.parity?.checks||[]).filter(x=>x.mode==='optimized_gpu');$('checks').innerHTML=list.length?list.map((x,i)=>`<button class="checkrow" data-check="${i}" style="width:100%;background:white;border:0;border-bottom:1px solid #eee;text-align:left"><span>${esc(x.case_id)}</span><span class="${x.pass?'pass':'fail'}">${x.pass?'PASS':'FAIL · 查看差异'}</span></button>`).join(''):'<p class="caption">等待独立验证</p>';document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const x=list[+b.dataset.check];showCheck(x)})}
function showCheck(x){const rows=(x.diffs||[]).map(d=>`<tr><td>${esc(d.column||d.kind)}</td><td>${esc(JSON.stringify(d.expected))}</td><td>${esc(JSON.stringify(d.actual))}</td><td>${d.column==='mean_ttft_ms'?'缺失 TTFT 不能补零；[10, null] 应为 10，补零变成 5':esc(d.kind)}</td></tr>`).join('');modal('检查详情 · '+x.case_id,`<p>运行 ${esc(current.id)} / attempt ${code.attempt??current.attempt??'—'} · ${x.pass?'通过':'失败，阻止测速与有效导出'}</p><table class="diff-table"><thead><tr><th>字段</th><th>参考值</th><th>候选值</th><th>规则</th></tr></thead><tbody>${rows||'<tr><td colspan="4">独立比较通过</td></tr>'}</tbody></table><details><summary>完整检查 JSON</summary><pre>${esc(JSON.stringify(x,null,2))}</pre></details>`)}
function render(s){current=s;$('runId').textContent=s.id;$('runStatus').textContent=(ACTIVE.has(s.status)?'活动 · ':'记录 · ')+s.status;$('runStatus').className='status '+(s.status==='FAILED'?'bad':ACTIVE.has(s.status)?'neutral':'');$('dataChip').textContent=Number(s.rows||0).toLocaleString()+' 行 · seed '+(s.seed||'待记录');$('scenario').value=s.scenario;
 const p=s.parity||{};$('speed').textContent=s.speedup?s.speedup.toFixed(2)+'×':'—';$('speedNote').textContent='预热后同构 CPU / GPU；不作为部署建议';$('parity').textContent=p.total?`${p.passed} / ${p.total}`:'—';$('parityNote').textContent=s.validation_status==='PASS'?'边界、全量与测量样本通过':p.total?'当前 attempt 边界验证':'尚未验证';$('semantics').textContent=s.validation_status||'PENDING';$('semanticsNote').textContent=s.candidate_id?'候选 '+s.candidate_id.slice(0,12):'尚未冻结候选';
 const profile=$('executionProfile').value;const d=s.deployment?.[profile];$('duration').textContent=d?d.recommended_backend.toUpperCase():'未验证';$('durationNote').textContent=d?`${profile} · 整个进程 CPU ${d.cpu_total_seconds.toFixed(2)}s / GPU ${d.gpu_total_seconds.toFixed(2)}s`:'所选部署模式尚无有效测量';
 const b=s.bench||{},max=Math.max(...Object.values(b).map(x=>x.median_seconds),.001);$('plot').innerHTML=Object.entries(names).map(([k,label])=>`<div class="barrow"><div class="barlabel"><span>${label}</span><strong>${b[k]?b[k].median_seconds.toFixed(4)+' s':'未测量'}</strong></div><div class="track"><div class="bar ${k==='optimized_gpu'?'gpu':k.startsWith('optimized')?'rewrite':''}" style="width:${b[k]?100*b[k].median_seconds/max:0}%"></div></div></div>`).join('')+`<div class="plotfoot">预热 1 次 / 测量 3 次；包含读取、聚合、写出与同步。<br><b>部署推荐独立计算：${d?profile+' → '+d.recommended_backend.toUpperCase():'所选模式未测量'}</b><br>${d?'新进程各测一次，未清文件缓存；常驻批次包含初始化和全部不同输入。':''}</div>`;
 $('codeNote').textContent='模型选择受审计策略与实验顺序；这里显示运行快照，原始模板不是模型生成的代码。';renderChecks();
 const events=s.events||[];$('stepCount').textContent=events.length+' 条';$('timeline').innerHTML=events.slice(-8).map(e=>`<div class="step ${['validation_failed','error'].includes(e.event_type)?'blocked':''}"><div class="steptitle"><span>${esc(e.stage)}</span><span>#${e.sequence}</span></div><p>${esc(e.message)}</p></div>`).join('');
 const valid=s.finalized&&s.validation_status==='PASS'&&d?.status==='MEASURED';$('decisionTitle').textContent=valid?'所选模式建议 '+d.recommended_backend.toUpperCase():s.status==='FINALIZING'?'正在收尾，尚不能导出':s.error?'运行未形成有效交付':'等待结果与部署测量';$('decisionText').textContent=valid?`候选 ${s.candidate_id.slice(0,12)} 与验证记录绑定。${profile} 的实际执行遵从 ${d.recommended_backend.toUpperCase()} 建议。`:s.error||events.at(-1)?.message||'尚未运行';$('decision').className='decision '+(s.status==='FAILED'?'bad':d?.recommended_backend==='cpu'?'warn':'');$('publishBtn').disabled=!valid||!!window.OFFLINE;$('deliveryWorkflow').disabled=!valid||!!window.OFFLINE;$('manifestPreview').textContent=JSON.stringify({run_id:s.id,candidate_id:s.candidate_id,validation_status:s.validation_status,execution_profile:profile,recommended_backend:d?.recommended_backend||'UNVERIFIED',finalized:s.finalized},null,2);activeUI();
}
async function loadAttempts(id,token){const list=await api('/api/runs/'+id+'/attempts');if(token!==selection||current?.id!==id)return;attempts=list;code=list.at(-1)||{};$('attemptSelect').innerHTML=list.map(a=>`<option value="${a.attempt}">attempt ${a.attempt} · ${a.candidate_id.slice(0,8)}</option>`).join('');$('attemptSelect').value=String(code.attempt??'');renderCode()}
function watch(id){if(source?.runId===id)return;if(source)source.close();const conn=new EventSource('/api/runs/'+id+'/events?after=0');conn.runId=id;source=conn;const refresh=async(done=false)=>{const s=await api('/api/runs/'+id);if(source!==conn)return;activeRun=ACTIVE.has(s.status)?s:null;activeUI();if(current?.id===id){render(s);await loadAttempts(id,selection)}if(done){conn.close();if(source===conn)source=null}};conn.onmessage=()=>refresh().catch(e=>toast(e.message));conn.addEventListener('done',()=>refresh(true).catch(e=>toast(e.message)));conn.onerror=()=>{if(source===conn)toast('活动任务连接中断，自动重连')}}
async function load(id,show=true){const token=++selection;const s=await api('/api/runs/'+id);if(token!==selection)return;attempts=[];code={};if(ACTIVE.has(s.status)){activeRun=s;watch(id)}render(s);await loadAttempts(id,token);if(show&&token===selection)page('work')}
$('runBtn').onclick=async()=>{try{if(activeRun)return toast('已有活动任务');if(!project)project=(await api('/api/projects',{})).id;const s=await api('/api/projects/'+project+'/runs',{scenario:$('scenario').value,execution_profile:$('executionProfile').value});await load(s.id)}catch(e){toast(e.message)}};
async function cancelActive(){try{const id=activeRun?.id;if(!id)return;await api('/api/runs/'+id+'/cancel',{});activeRun=null;activeUI();await load(id)}catch(e){toast(e.message)}}
$('cancelBtn').onclick=cancelActive;
$('scenario').onchange=()=>{if(activeRun){$('scenario').value=current?.scenario||activeRun.scenario;return}++selection;attempts=[];code={};render({id:'未运行',scenario:$('scenario').value,status:'READY',rows:{large:5000000,small:1000,fail:1000,repair:1000000,standard:1000000}[$('scenario').value],events:[]});renderCode()};
$('executionProfile').onchange=()=>{if(current)render(current)};
$('contractBtn').onclick=async()=>{try{const c=await api('/api/contract');modal('统计契约 · 已冻结',`<p>仅适用于本项目固定结构合成日志；SHA-256 ${esc(c.sha256)}</p><pre>${esc(c.text)}</pre>`)}catch(e){toast(e.message)}};
async function details(){if(!current?.id||current.id==='未运行')return toast('尚无运行记录');const a=await api('/api/runs/'+current.id+'/artifacts');modal('运行证据 · '+current.id,`<p>候选 ${esc(current.candidate_id||'未冻结')}；修复 ${current.repairs||0} 轮。故障注入：${current.fault_injection?'是':'否'}。</p><p>请选择检查项查看具体参考值与候选值。这里保留完整原始文件。</p><details><summary>展开完整运行 JSON</summary><pre>${esc(JSON.stringify(current,null,2))}</pre></details>`+a.map(f=>`<p><a href="${esc(f.url)}">${esc(f.name)}</a></p>`).join(''))}
$('evidenceBtn').onclick=()=>details().catch(e=>toast(e.message));$('reportBtn').onclick=$('evidenceBtn').onclick;$('deliveryReport').onclick=$('evidenceBtn').onclick;
function exportReview(){if(!current)return;const id=current.id,profile=$('executionProfile').value;modal('审核本地工作流导出',`<p>运行 ${esc(id)} · 候选 ${esc(current.candidate_id)}。</p><p>执行模式 ${profile}，建议 ${esc(current.deployment?.[profile]?.recommended_backend||'未验证')}。服务端核验历史快照、策略与判卷规则后导出。仅本地文件，不上传。</p>`,async()=>{try{const r=await api('/api/runs/'+id+'/approval',{kind:'local_export',approved:true,execution_profile:profile});close();window.location.assign(r.artifact_url);toast('已导出绑定快照：'+r.sha256.slice(0,16))}catch(e){toast(e.message)}})}
$('publishBtn').onclick=exportReview;$('deliveryWorkflow').onclick=exportReview;
$('downloadMock').onclick=()=>{if(current?.id&&current.id!=='未运行')window.location.assign('/api/runs/'+current.id+'/download/run.json')};
async function history(){const list=await api('/api/runs');const active=list.find(s=>ACTIVE.has(s.status));if(active){activeRun=active;watch(active.id)}else if(!source)activeRun=null;activeUI();$('historyRows').innerHTML=list.map(s=>`<tr><td class="mono">${esc(s.id)}</td><td>${Number(s.rows||0).toLocaleString()} 行 · ${esc(s.scenario)}</td><td>${esc(s.status)}</td><td>${s.speedup?s.speedup.toFixed(2)+'× 暖态':'—'}</td><td><button class="btn sm" data-run="${esc(s.id)}">查看实测</button></td></tr>`).join('');document.querySelectorAll('[data-run]').forEach(e=>e.onclick=()=>load(e.dataset.run));document.querySelector('[data-page=history] .count').textContent=list.length}
async function skills(){const list=await api('/api/skills');$('skillgrid').innerHTML=list.map(s=>`<div class="skillcard"><span class="status">${esc(s.kind)}</span><h3>${esc(s.name)}</h3><p>${esc(s.text?.split('\n\n')[2]||'NVIDIA 固定提交原版技能；保留归属，不宣称认证。')}</p><div class="skillmeta">SHA-256 ${esc(s.sha256)}</div></div>`).join('')}
(async()=>{try{const list=await api('/api/runs');if(list.length)await load((list.find(s=>ACTIVE.has(s.status))||list[0]).id,false);else $('scenario').onchange();await history()}catch(e){toast(e.message)}})();
